### ISSUE TITLE
Couldn't start Java Language Server

### ISSUE THREAD

**Issue by MisterZet** [georgewfraser/java-language-server#140]
Hello after tree-sitter fix, there's new issue.
mainThreadExtensionService.ts:66 Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)
	at c:\Users\Brian\.vscode-insiders\extensions\georgewfraser.vscode-javac-0.2.32\node_modules\vscode-languageclient\lib\main.js:357:40

**Comment by MisterZet** [comment]
@georgewfraser

**Comment by georgewfraser** [comment]
Hmm, I think there's something VSCode on windows doesn't like about the async init function. It might be this `await`:

https://github.com/georgewfraser/java-language-server/blob/b75671304e9611c2d64511310d1e6caef0834dfb/lib/extension.ts#L128

It's a bit tricky for me to troubleshoot on Windows because I don't have a windows machine handy. Could you clone the repo and try commenting out:

```
await loadStyles();
applySemanticColors();
```

and the doing `./scripts/build.sh` and see if that fixes it?

**Comment by MisterZet** [comment]
Will do, maybe you have got a discord? Would be easier to communicate?

**Comment by georgewfraser** [comment]
I think github issues is the best way.

**Comment by MisterZet** [comment]
Alright, I’ll do that whenever I’m on my computer.

**Comment by MisterZet** [comment]
Getting same error

**Comment by kigero** [comment]
I'm getting the same error with v0.2.33, and took a quick look at what's going on.  It looks like the language server isn't starting up at all from VSCode on windows.  The command that it's trying to run in order to launch the language server is `C:\Users\username\.vscode\extensions\georgewfraser.vscode-javac-0.2.33\dist\lang_server_windows.sh`, and looking at this file it is indeed a shell script.  Is this supposed to be working on windows?  I would have expected a bat file, but maybe there's some magic to run this on windows that I'm not aware of.

I hacked up a quick bat file based on the script and was able to get the language server to run successfully from VSCode, but then I started getting errors like this, so I suspect that there's more going on than just getting the server to start:

```
mainThreadExtensionService.ts:66 Error: Message header must separate key and value using :
	at c:\Users\username\.vscode\extensions\georgewfraser.vscode-javac-0.2.33\node_modules\vscode-jsonrpc\lib\messageReader.js:57:23
	at Array.forEach (<anonymous>)
	at MessageBuffer.tryReadHeaders (c:\Users\username\.vscode\extensions\georgewfraser.vscode-javac-0.2.33\node_modules\vscode-jsonrpc\lib\messageReader.js:54:17)
	at StreamMessageReader.onData (c:\Users\username\.vscode\extensions\georgewfraser.vscode-javac-0.2.33\node_modules\vscode-jsonrpc\lib\messageReader.js:157:43)
	at Socket.<anonymous> (c:\Users\mcminn\.username\extensions\georgewfraser.vscode-javac-0.2.33\node_modules\vscode-jsonrpc\lib\messageReader.js:148:18)
	at Socket.emit (events.js:203:13)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:276:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by georgewfraser** [comment]
We should really get rid of the tree-sitter parts, in favor of using the native semantic coloring features that have been added to vscode.

**Comment by 8746070404** [comment]
couldnt start java language server
