### ISSUE TITLE
newer Bazel and build with Bazel

### ISSUE THREAD

**Issue by brown** [georgewfraser/java-language-server#178]
I've been thoroughly enjoying using java-language-server to edit Java code using GNU Emacs and eglot.  Thanks very much for making the code available.

In my spare time I have been working on two things, using Bazel to compile java-language-server and upgrading the Bazel support in InferConfig so that it works with recent Bazel releases.  Are you interested in either of these changes?

**Comment by jinyius** [comment]
@brown i'm hitting an issue atm where i'm using bazel 4.0 (from homebrew on a mac), and i'm getting this proto parse exception being thrown in InferConfig.readActionGraph:

```
15:12:27.838	SEVERE	Main main	com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
java.lang.RuntimeException: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at org.javacs.InferConfig.readActionGraph(InferConfig.java:415)
	at org.javacs.InferConfig.bazelAQuery(InferConfig.java:376)
	at org.javacs.InferConfig.bazelClasspath(InferConfig.java:273)
	at org.javacs.InferConfig.classPath(InferConfig.java:76)
	at org.javacs.JavaLanguageServer.createCompiler(JavaLanguageServer.java:106)
	at org.javacs.JavaLanguageServer.compiler(JavaLanguageServer.java:39)
	at org.javacs.JavaLanguageServer.lint(JavaLanguageServer.java:61)
	at org.javacs.JavaLanguageServer.doAsyncWork(JavaLanguageServer.java:523)
	at org.javacs.lsp.LSP.connect(LSP.java:247)
	at org.javacs.Main.main(Main.java:30)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message had invalid UTF-8.
	at com.google.protobuf.InvalidProtocolBufferException.invalidUtf8(InvalidProtocolBufferException.java:141)
	at com.google.protobuf.Utf8$DecodeUtil.handleTwoBytes(Utf8.java:1909)
	at com.google.protobuf.Utf8$DecodeUtil.access$700(Utf8.java:1883)
	at com.google.protobuf.Utf8$UnsafeProcessor.decodeUtf8(Utf8.java:1411)
	at com.google.protobuf.Utf8.decodeUtf8(Utf8.java:340)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readStringRequireUtf8(CodedInputStream.java:2296)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$DepSetOfFiles.<init>(AnalysisProtos.java:11294)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$DepSetOfFiles$1.parsePartialFrom(AnalysisProtos.java:12275)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$DepSetOfFiles$1.parsePartialFrom(AnalysisProtos.java:12269)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2364)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$ActionGraphContainer.<init>(AnalysisProtos.java:218)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$ActionGraphContainer$1.parsePartialFrom(AnalysisProtos.java:2761)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$ActionGraphContainer$1.parsePartialFrom(AnalysisProtos.java:2755)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:232)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:237)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:332)
	at com.google.devtools.build.lib.analysis.AnalysisProtos$ActionGraphContainer.parseFrom(AnalysisProtos.java:668)
	at org.javacs.InferConfig.readActionGraph(InferConfig.java:381)
	... 9 more
```

do your changes address differences in the action graph output from bazel?

**Comment by brown** [comment]
The default action graph output format is different in recent versions of
Bazel.  For now you should be able to work around the problem by adding
something like "aquery --incompatible_proto_output_v2=false" to your
.bazelrc file.

**Comment by jinyius** [comment]
hmm... i actually am going through and moving to the v2 proto.  i guess that flag is easier.

**Comment by georgewfraser** [comment]
While I personally am a big bazel fan, it's not widely known, and I think changing the build from maven to bazel would make this project less contributor-friendly.

**Comment by jinyius** [comment]
what about just updating InferConfig to handle the new bazel proto format?  don't need to update this language server's build setup.

**Comment by georgewfraser** [comment]
Yes, very happy to merge a PR doing that!

**Comment by 007kevin** [comment]
Off topic but @brown could you share the eglot client config to integrate with java-language-server? Thanks.

**Comment by brown** [comment]
Replying to George's comment above ... 

I wasn't suggesting that the build be switched from Maven to Bazel.  Rather, I was asking whether there is interest in providing Bazel BUILD files, perhaps even on a bazel-build branch, which allow the project to be built using Bazel in addition to Maven.  If so, I'm happy to supply a push request.

Replying to 007kevin ...

Here is my eglot configuration for using java-language-server.

```
(with-eval-after-load 'eglot
  (define-key eglot-mode-map (kbd "C-c d") 'eldoc)
  (define-key eglot-mode-map (kbd "C-c f") 'eglot-code-action-quickfix)
  (define-key eglot-mode-map (kbd "C-c o") 'eglot-code-action-organize-imports)
  (define-key eglot-mode-map (kbd "C-c r") 'eglot-rename)

  (push '(java-mode . ("java-language-server")) eglot-server-programs))
```
I have a shell script called java-language-server that executes dist/lang_server_linux.sh.

Additionally, in the code directory where I am working, I create a .dir-locals.el file that tells eglot what classpath and Java home directory to provide to the language server.  It looks something like this for Java and Python:

```
((java-mode                 
  (eglot-workspace-configuration       
   (:java                                       
    (:classPath . ("/path/to/foo.jar" "/path/to/bar.jar")))))     
 (python-mode                                        
  (eglot-workspace-configuration      
   (:pyls                              
    (:plugins         
     (:jedi                       
      (:environment . "/path/to/python-binary")))))))
```

**Comment by 007kevin** [comment]
Thanks for sharing @brown. For generating the classPath, are you using some kind of bazel query or aspects?

**Comment by jinyius** [comment]
heads up, but bazel 5.0 breaks aquery now since it's only the aquery v2 protos:

https://github.com/bazelbuild/bazel/blob/3a8d07d0e53742ce7937b332b09191cf83d4083b/src/main/java/com/google/devtools/build/lib/query2/aquery/AqueryOptions.java#L83

**Comment by jinyius** [comment]
tested #207, and it works for me.  thanks @draftcode
