### ISSUE TITLE
null element into warnUnused causes exception that probably should be skipped

### ISSUE THREAD

**Issue by jinyius** [georgewfraser/java-language-server#180]
this issue sprang up in an private repo, so i'm not sure how easily i can create a repo case, but the exception that is thrown in javacs/markup/ErrorProvider.warnUnused probably shouldn't cause the entire server to die.

i worked around the issue by logging some extra detail and skipping un-warned elements (i can make this a pr if you want):

```
diff --git a/src/main/java/org/javacs/markup/ErrorProvider.java b/src/main/java/org/javacs/markup/ErrorProvider.java
index 1c4d3412..ee3e0f72 100644
--- a/src/main/java/org/javacs/markup/ErrorProvider.java
+++ b/src/main/java/org/javacs/markup/ErrorProvider.java
@@ -6,6 +6,8 @@ import java.nio.file.Paths;
 import java.util.ArrayList;
 import java.util.HashMap;
 import java.util.List;
+import java.util.logging.Level;
+import java.util.logging.Logger;
 import java.util.regex.Pattern;
 import javax.lang.model.element.Element;
 import javax.tools.JavaFileObject;
@@ -49,8 +51,13 @@ public class ErrorProvider {
         var result = new ArrayList<org.javacs.lsp.Diagnostic>();
         var warnUnused = new WarnUnused(task.task);
         warnUnused.scan(root, null);
+        LOG.info("unused: " + warnUnused.notUsed());
         for (var unusedEl : warnUnused.notUsed()) {
-            result.add(warnUnused(unusedEl));
+            try {
+                result.add(warnUnused(unusedEl));
+            } catch (Exception e) {
+                LOG.log(Level.WARNING, e.getMessage(), e);
+            }
         }
         return result;
     }
@@ -189,4 +196,6 @@ public class ErrorProvider {
         result.range = RangeHelper.range(root, start, end);
         return result;
     }
+
+    private static final Logger LOG = Logger.getLogger("ErrorProvider");
 }
```

i probably should investigate why null is being detected as unused a bit more, but don't have time to dive deep yet.

here's the output of the logging above for the file that hits this:

```
20:04:26.015	INFO	ErrorProvider unusedWarnings	unused: [null, flatEventBuilder, flatEventBuilder, builder, user, env, context, dedupedImpression, rawRequestInput, dedupedViews, collector, rawUserInput, factory, rawInsertionInput, rawClickInput, viewRequestInsertionImpression, context, factory, viewRequestInsertionImpressions, viewRequestInsertionImpression, factory, factory, rawImpressionInput, builder, field, collector, rawInsertionInput, env, dedupedInsertion, rawRequestInput, rawClickInput, context, rawRequestInput, collector, viewRequestInsertionImpressionClicks, userViewRequestInsertionImpressionClicks, original, context, viewRequestInsertionImpression, rawClickInput, viewRequestInsertions, factory, userViewRequestInsertionImpressions, avroProtoClass, rawCohortMembershipInput, flatEventBuilder, rawViewInput, factory, rawImpressionInput, rawInsertionInput, rawViewInput, view, context, click, rawRequestInput, user, collector, env, factory, idBuilder, collector, env, rawViewInput, env, rawClickInput, factory, config, flatEventBuilder, insertion, rawInsertionInput, request, viewRequestInsertion, env, flatEventBuilder, config, env, rawUserInput, collector, dedupedRequests, rawCohortMembershipInput, rawImpressionInput, idBuilder, env, flatEventBuilder, rawUserInput, impression, firstUserInput, env, builder, viewRequests, builder, rawUserInput, viewRequest, dedupedClick, context, rawImpressionInput, rawViewInput, consumer, env]
20:04:26.015	WARNING	ErrorProvider unusedWarnings	null has no path
java.lang.RuntimeException: null has no path
	at org.javacs.markup.ErrorProvider.warnUnused(ErrorProvider.java:132)
	at org.javacs.markup.ErrorProvider.unusedWarnings(ErrorProvider.java:57)
	at org.javacs.markup.ErrorProvider.errors(ErrorProvider.java:32)
	at org.javacs.JavaLanguageServer.lint(JavaLanguageServer.java:64)
	at org.javacs.JavaLanguageServer.doAsyncWork(JavaLanguageServer.java:523)
	at org.javacs.lsp.LSP.connect(LSP.java:247)
	at org.javacs.Main.main(Main.java:30)

20:04:26.102	INFO	JavaLanguageServer lint	...published in 2999 ms
```
```

**Comment by georgewfraser** [comment]
This has been fixed in a recent PR.

**Comment by jinyius** [comment]
> This has been fixed in a recent PR.

mind linking the pull/commit?  curious to see what the fix was (to compare to my local solution/workaround).

**Comment by georgewfraser** [comment]
https://github.com/georgewfraser/java-language-server/pull/175
