### ISSUE TITLE
Couldn't start client Java Language Server

### ISSUE THREAD

**Issue by OOOHA** [georgewfraser/java-language-server#185]
Issue Type: <b>Bug</b>

It happens again today.
I have closed the [#182 ](https://github.com/georgewfraser/java-language-server/issues/182), cause it's been a long with no error.
Again I used the Extension Bisect to found the Extension error.
This error pop up as soon as I open a java project.

Extension version: 0.2.37
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.00GB free)|
|Process Argv|--crash-reporter-id 6e0a0302-b09c-4c20-8e81-5fa91decd80f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt700cf:30270857
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
vspre833cf:30267465
vsdfh931cf:30280410
vshan820cf:30276953

```

</details>

**Comment by OOOHA** [comment]
This is the log.


workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.go.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/go/syntaxes/go.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/go.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/cpp.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.ruby.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/ruby/syntaxes/ruby.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/ruby.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.rust.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/rust/syntaxes/rust.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/rust.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.ts.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/typescript-basics/syntaxes/TypeScript.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/typescript.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope go.mod.
Old grammar file: file:///c%3A/Users/henry/.vscode/extensions/golang.go-0.23.3/syntaxes/go.mod.tmGrammar.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/golang.go-nightly-2021.3.2321/syntaxes/go.mod.tmGrammar.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope go.sum.
Old grammar file: file:///c%3A/Users/henry/.vscode/extensions/golang.go-0.23.3/syntaxes/go.sum.tmGrammar.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/golang.go-nightly-2021.3.2321/syntaxes/go.sum.tmGrammar.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.5/syntaxes/cpp.embedded.macro.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/henry/.vscode/extensions/georgewfraser.vscode-tree-sitter-0.1.26/textmate/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.5/syntaxes/cpp.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.c.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/c.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.5/syntaxes/c.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.objcpp.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/objective-c/syntaxes/objective-c%2B%2B.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.5/syntaxes/objcpp.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.objc.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/objective-c/syntaxes/objective-c.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.5/syntaxes/objc.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:1870 Overwriting grammar scope name to file mapping for scope source.java.
Old grammar file: file:///c%3A/Users/henry/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/java/syntaxes/java.tmLanguage.json.
New grammar file: file:///c%3A/Users/henry/.vscode/extensions/redhat.java-0.76.0/syntaxes/java.tmLanguage.json
register @ workbench.desktop.main.js:sourcemap:1870
workbench.desktop.main.js:sourcemap:62 [Extension Host] (node:9820) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
v @ workbench.desktop.main.js:sourcemap:62
workbench.desktop.main.js:sourcemap:1857 Activating extension 'golang.go-nightly' failed: command 'go.workspace.isTrusted.toggle' already exists.
_logMessageInConsole @ workbench.desktop.main.js:sourcemap:1857
workbench.desktop.main.js:sourcemap:2765 Extension Host
workbench.desktop.main.js:sourcemap:2765 {  message: 'Starting Java server with: C:\\Program Files\\Java\\jdk-15.0.2\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar c:\\Users\\henry\\.vscode\\extensions\\redhat.java-0.76.0\\server\\plugins\\org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration c:\\Users\\henry\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\0.76.0\\config_ss_win -data c:\\Users\\henry\\AppData\\Roaming\\Code\\User\\workspaceStorage\\b8047788548420bdd25ef68fb1a09a37\\redhat.java\\ss_ws',  level: 'info',  timestamp: '2021-03-25 12:29:36.097'}
workbench.desktop.main.js:sourcemap:2765 Extension Host
workbench.desktop.main.js:sourcemap:2765 {  message: 'Starting Java server with: C:\\Program Files\\Java\\jdk-15.0.2\\bin\\java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -DwatchParentProcess=false -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -jar c:\\Users\\henry\\.vscode\\extensions\\redhat.java-0.76.0\\server\\plugins\\org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar -configuration c:\\Users\\henry\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.java\\0.76.0\\config_win -data c:\\Users\\henry\\AppData\\Roaming\\Code\\User\\workspaceStorage\\b8047788548420bdd25ef68fb1a09a37\\redhat.java\\jdt_ws',  level: 'info',  timestamp: '2021-03-25 12:29:36.237'}{  message: 'WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.jpackage\r\n',  level: 'info',  timestamp: '2021-03-25 12:29:36.333'}{  message: 'WARNING: Using incubator modules: jdk.incubator.jpackage, jdk.incubator.foreign\r\n',  level: 'info',  timestamp: '2021-03-25 12:29:36.423'}
workbench.desktop.main.js:sourcemap:62 [Extension Host] [vscode-icons] v11.2.0 activated!
workbench.desktop.main.js:sourcemap:626   ERR The request (id: 1, method: 'textDocument/documentSymbol') has been cancelled: Error: The request (id: 1, method: 'textDocument/documentSymbol') has been cancelled
	at c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:76464
	at c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:456:21)
workbench.desktop.main.js:sourcemap:626   ERR The request (id: 2, method: 'textDocument/documentSymbol') has been cancelled: Error: The request (id: 2, method: 'textDocument/documentSymbol') has been cancelled
	at c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:76464
	at c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:76758
	at Immediate.<anonymous> (c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:77117)
	at processImmediate (internal/timers.js:456:21)
workbench.desktop.main.js:sourcemap:626   ERR Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:80768)
	at Object.dispose (c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:140455)
	at c:\Users\henry\.vscode\extensions\redhat.java-0.76.0\dist\extension.js:1:137111
DevTools failed to load SourceMap: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/2b9aebd5354a3629c3aba0a5f5df49f43d6689f8/node_modules/windows-process-tree/lib/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by OOOHA** [comment]
Fixed now
