### ISSUE TITLE
Compiler is already in-use!

### ISSUE THREAD

**Issue by s759labs** [georgewfraser/java-language-server#192]
I am trying out the java language server with monaco editor. I get correct auto-complete options for couple of times and then it stops. I see the following exception logged. Any advice as to what could be causing this issue?

`JAVA Server: 22:18:37.543       SEVERE  Main main       Compiler is already in-use!
java.lang.RuntimeException: Compiler is already in-use!
        at org.javacs.ReusableCompiler.getTask(ReusableCompiler.java:111)
        at org.javacs.CompileBatch.batchTask(CompileBatch.java:105)
        at org.javacs.CompileBatch.<init>(CompileBatch.java:30)
        at org.javacs.JavaCompilerService.doCompile(JavaCompilerService.java:76)
        at org.javacs.JavaCompilerService.loadCompile(JavaCompilerService.java:67)
        at org.javacs.JavaCompilerService.compileBatch(JavaCompilerService.java:93)
        at org.javacs.JavaCompilerService.compile(JavaCompilerService.java:349)
        at org.javacs.JavaCompilerService.compile(JavaCompilerService.java:344)
        at org.javacs.JavaLanguageServer.lint(JavaLanguageServer.java:61)
        at org.javacs.JavaLanguageServer.doAsyncWork(JavaLanguageServer.java:526)
        at org.javacs.lsp.LSP.connect(LSP.java:247)
        at org.javacs.Main.main(Main.java:30)
`

**Comment by babutabhavya** [comment]
+1

**Comment by amitbkumar** [comment]
Hey @s759labs, How are you using jls with monaco editor? which command you are using to start server?

**Comment by chaitanya71998** [comment]
@s759labs can you share details for monaco editor integration

> Hey @s759labs, How are you using jls with monaco editor? which command you are using to start server?
