### ISSUE TITLE
Completion error

### ISSUE THREAD

**Issue by StarkZhidian** [georgewfraser/java-language-server#211]
org.javacs.Main startServer	null
    java.lang.AssertionError
        at com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at com.sun.tools.javac.util.Assert.check(Assert.java:46)
        at com.sun.tools.javac.code.Scope$ScopeImpl.<init>(Scope.java:317)
        at com.sun.tools.javac.code.Scope$ScopeImpl.<init>(Scope.java:324)
        at com.sun.tools.javac.code.Scope$ScopeImpl.dupUnshared(Scope.java:377)
        at com.sun.tools.javac.comp.MemberEnter.methodEnv(MemberEnter.java:239)
        at com.sun.tools.javac.comp.MemberEnter.getMethodEnv(MemberEnter.java:436)
        at com.sun.tools.javac.api.JavacTrees.getAttrContext(JavacTrees.java:895)
        at com.sun.tools.javac.api.JavacTrees.getScope(JavacTrees.java:781)
        at com.sun.tools.javac.api.JavacTrees.getScope(JavacTrees.java:163)
        at org.javacs.CompileFocus.scopeMembers(CompileFocus.java:566)
        at org.javacs.CompileFocus.completeScopeIdentifiers(CompileFocus.java:693)
        at org.javacs.CompileFocus.completeIdentifiers(CompileFocus.java:184)
        at org.javacs.JavaLanguageServer.completion(JavaLanguageServer.java:372)
        at org.javacs.lsp.LSP.connect(LSP.java:311)

**Comment by StarkZhidian** [comment]
This is my test code:

class Main {
 
 public static void main(String[] args) {
  //System.out.println("Hello World!");
  int aa;
  a
  return;
 }
}
