### ISSUE TITLE
Continues to crash on 0.2.41, rollback to 0.2.40 doesn't crash

### ISSUE THREAD

**Issue by victorchentw** [georgewfraser/java-language-server#218]
[Info  - 10:51:12 AM] Connection to server got closed. Server will restart.
10:51:13.054	SEVERE	Main main	com/google/gson/JsonElement
java.lang.NoClassDefFoundError: com/google/gson/JsonElement
	at org.javacs.Main.main(Main.java:30)
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonElement
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more

[Error - 10:51:13 AM] Connection to server got closed. Server will not be restarted.

**Comment by georgewfraser** [comment]
What OS are you on?
