### ISSUE TITLE
Error: Module java.sql not found

### ISSUE THREAD

**Issue by codenester** [georgewfraser/java-language-server#222]
When I was trying to install it using ./scripts/link_linux.sh, I got an error below:

Error: Module java.sql not found
java.lang.module.FindException: Module java.sql not found
	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
	at java.base/java.lang.module.Resolver.resolve(Resolver.java:129)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:217)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:536)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:424)
	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:276)
	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:55)
	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:33)

Any solution please

**Comment by arrky** [comment]
You can try running the following commands:
```sh
./scripts/download_linux_jdk.sh
rm -rf dist/linux
./jdks/linux/jdk-18/bin/jlink \
  --module-path ./jdks/linux/jdk-18/bin/jmods \
  --add-modules java.base,java.compiler,java.logging,java.sql,java.xml,jdk.compiler,jdk.jdi,jdk.unsupported,jdk.zipfs \
  --output dist/linux \
  --no-header-files \
  --no-man-pages \
  --compress 2
```

Or you can edit the script as in #220.
