### ISSUE TITLE
The Java Language Server server crashed

### ISSUE THREAD

**Issue by jackzhenguo** [georgewfraser/java-language-server#65]
I used vscode and wanted to build environment for Java, but it fails, following:

![image](https://user-images.githubusercontent.com/20391209/41226477-2bb374b0-6da4-11e8-9c43-a583fc8805bb.png)

Could you help me to solve it? Thank you very much!

**Comment by nreedFA** [comment]
I've just encountered the same issue - Win10.

**Comment by Tomboyo** [comment]
I have also encountered this issue. The error message appears as soon as I open VSCode. ALmost looks like it might be trying to read a file from the C: drive? I get this error exactly 5 times (corresponding to the number of attemps reported by VSCode).

About VS Code output:
Version: 1.25.1
Commit: 1dfc5e557209371715f655691b1235b6b26a06be
Date: 2018-07-11T15:43:53.668Z
Electron: 1.7.12
Chrome: 58.0.3029.110
Node.js: 7.9.0
V8: 5.8.283.38
Architecture: x64

I am running on Windows 10.

[extension-output-#2.log](https://github.com/georgewfraser/vscode-javac/files/2206446/extension-output-.2.log)

**Comment by Tomboyo** [comment]
Speculation on the the root cause of my version of the bug: LangTools passes `System.getProperty("java.class.path");` output` to `ChildFirstClassLoader.fromClassPath`, which splits it by the path separator `\` (in Windows) and then tries to shove that into a `URL[]`. But the string `C:` is not a valid URL, so that fails. Don't have time right now to follow up with a test that this is indeed what is going on, but I can check this out when I get home.

**Comment by evansdarryl3** [comment]
I'm having the same issue as "jackzhenguo" saying my server has crashed 5 times. 


java.lang.UnsupportedClassVersionError: ex112 has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" 
[Done] exited with code=1 in 1.019 seconds

**Comment by georgewfraser** [comment]
@evansdarryl3 You need to install java 10 or 11
